### ISSUE TITLE
something is wrong

### ISSUE THREAD

**Issue by leehave** [brunjo/rowGrid.js#27]
There is a problem, if there will be repeatedly updated display random problem, sometimes only two maps, review pictures have been loaded

**Comment by brunjo** [comment]
What exactly isn't working? Could you send me an example where it doesn't work and how to reproduce the error? Thanks.

**Comment by brunjo** [comment]
I think, the problem is, that you don't specify the width and height attribute on the images in the example you send me via email. The images should look like `<img src="…" width="500" height ="500">`.

Another way to solve the problem would be to wait until all images are loaded before you call the rowGrid method:
```
$(window).on('load', function() {
    $('.pic_content').rowGrid(options);
});
```

**Comment by leehave** [comment]
great ,thanks for you
